language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
    - locale-gen nl_NL.UTF-8
    - locale-gen en_GB.UTF-8
    - update-locale
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit --colors --coverage-text --verbose
